[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
markers = [
    "argv",
    "deck",
    "hand",
    "hands",
    "msg",
    "validator",
]